"""PX4-related constants and masks.

Centralises magic numbers so other modules can import them cleanly.
"""
# NAVIGATION_STATE from msg/VehicleStatus.msg
NAV_STATE_MANUAL = 0
NAV_STATE_ALTCTL = 1
NAV_STATE_POSCTL = 2
NAV_STATE_AUTO_MISSION = 3
NAV_STATE_AUTO_LOITER = 4
NAV_STATE_AUTO_RTL = 5
NAV_STATE_AUTO_LANDENGFAIL = 8
NAV_STATE_ACRO = 10
NAV_STATE_DESCEND = 12
NAV_STATE_TERMINATION = 13
NAV_STATE_OFFBOARD = 14
NAV_STATE_STAB = 15
NAV_STATE_AUTO_TAKEOFF = 17
NAV_STATE_AUTO_LAND = 18
NAV_STATE_AUTO_FOLLOW_TARGET = 19
NAV_STATE_AUTO_PRECLAND = 20

# PX4 custom main modes
PX4_CUSTOM_MAIN_MODE_MANUAL = 1
PX4_CUSTOM_MAIN_MODE_ALTCTL = 2
PX4_CUSTOM_MAIN_MODE_POSCTL = 3
PX4_CUSTOM_MAIN_MODE_AUTO = 4
PX4_CUSTOM_MAIN_MODE_ACRO = 5
PX4_CUSTOM_MAIN_MODE_OFFBOARD = 6
PX4_CUSTOM_MAIN_MODE_STABILIZED = 7

# AUTO sub-modes
PX4_CUSTOM_SUB_MODE_AUTO_LOITER = 1
PX4_CUSTOM_SUB_MODE_AUTO_MISSION = 2
PX4_CUSTOM_SUB_MODE_AUTO_RTL = 3
PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF = 4
PX4_CUSTOM_SUB_MODE_AUTO_LAND = 5
PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET = 6
PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND = 9

# COMMAND_ACK results (MAVLink common.xml)
ACK_RESULT_NAMES = {
    0: "ACCEPTED",
    1: "TEMPORARILY_REJECTED",
    2: "DENIED",
    3: "UNSUPPORTED",
    4: "FAILED",
    5: "IN_PROGRESS",
    6: "CANCELLED",
}

# Bitmasks for SET_POSITION_TARGET_LOCAL_NED type_mask
POS_TARGET_MASK_VEL_IGNORE = 8 | 16 | 32
POS_TARGET_MASK_ACC_IGNORE = 64 | 128 | 256
POS_TARGET_MASK_YAW_IGNORE = 1024
POS_TARGET_MASK_YAW_RATE_IGNORE = 2048

# Default: position active, velocity/accel/yaw_rate ignored, yaw active
DEFAULT_POS_TYPE_MASK = (
    POS_TARGET_MASK_VEL_IGNORE
    | POS_TARGET_MASK_ACC_IGNORE
    | POS_TARGET_MASK_YAW_RATE_IGNORE
)
